---
extends: default

rules:
  line-length:
    max: 150
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: true
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  .venv/
  node_modules/
  .git/
  *.md
