# -*- mode: python ; coding: utf-8 -*-
# ═══════════════════════════════════════════════════════════════════════════════
# NebulaCompute Build Spec File
# Generated by NebulaCompute Build System v2.0
# نظام بناء NebulaCompute - ملف الإعدادات
# ═══════════════════════════════════════════════════════════════════════════════
#
# Build Configuration:
#   Mode: fast
#   Version: d30a123
#   Platform: linux
#   One-File: True
#   Console: False
#
# Generated: 2026-01-03T23:52:02.023939
# ═══════════════════════════════════════════════════════════════════════════════

from pathlib import Path
from PyInstaller.utils.hooks import collect_all

# Data files
datas = [(r'/home/user/theEnd/src/distributed_cluster/desktop/resources', 'distributed_cluster/desktop/resources'), (r'/home/user/theEnd/config', 'config')]

# Binary files
binaries = []

# Hidden imports
hiddenimports = [
    # Core Qt
    'PySide6.QtCore', 'PySide6.QtGui', 'PySide6.QtWidgets', 'PySide6.QtCharts',
    'PySide6.QtNetwork', 'PySide6.QtSvg', 'PySide6.QtSvgWidgets',
    # Desktop app
    'distributed_cluster', 'distributed_cluster.desktop', 'distributed_cluster.desktop.main',
    'distributed_cluster.desktop.main_window', 'distributed_cluster.desktop.app_entry',
    'distributed_cluster.desktop.api', 'distributed_cluster.desktop.api.client',
    'distributed_cluster.desktop.views', 'distributed_cluster.desktop.widgets',
    'distributed_cluster.desktop.resources',
    # Models
    'distributed_cluster.models', 'distributed_cluster.models.job',
    'distributed_cluster.models.worker', 'distributed_cluster.models.resources',
    # Core
    'distributed_cluster.core', 'distributed_cluster.core.config',
    # Network
    'httpx', 'httpx._transports', 'httpx._transports.default',
    'websockets', 'websockets.client', 'websockets.legacy', 'websockets.legacy.client',
    'httpcore', 'h11', 'anyio', 'anyio._backends', 'anyio._backends._asyncio', 'sniffio',
    # Standard library
    'asyncio', 'json', 'datetime', 'dataclasses', 'enum', 'typing', 'pathlib',
    'uuid', 'threading', 'queue', 'collections', 'ssl', 'certifi', 'qasync',
]

# Collect all from packages

tmp_ret = collect_all('PySide6')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]

tmp_ret = collect_all('httpx')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]

tmp_ret = collect_all('websockets')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]

# jaraco is not needed for basic functionality
# tmp_ret = collect_all('jaraco')
# datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]

# pkg_resources causes issues
# tmp_ret = collect_all('pkg_resources')
# datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]

tmp_ret = collect_all('certifi')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]


# Analysis
a = Analysis(
    [r'/home/user/theEnd/src/distributed_cluster/desktop/app_entry.py'],
    pathex=[r'/home/user/theEnd/src'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['jupyter', 'tensorflow', 'tk', 'pytest', 'test', '_tkinter', 'tcl', 'scipy', 'pandas', 'keras', 'pydoc', 'numpy', 'torch', 'setuptools', 'tests', 'doctest', 'matplotlib', 'unittest', 'wx', 'distutils', 'wheel', 'pdb', 'pip', 'PyQt5', 'sklearn', 'notebook', 'PIL.ImageTk', 'IPython', 'tkinter', 'PyQt6', 'cryptography', 'cryptography.hazmat', 'cryptography.hazmat.backends', 'cryptography.hazmat.backends.openssl', 'jaraco', 'pkg_resources'],
    noarchive=False,
    optimize=0,
)

# Create PYZ archive
pyz = PYZ(a.pure)

# Create executable

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='NebulaCompute',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=[r'/home/user/theEnd/src/distributed_cluster/desktop/resources/icon.ico'],
)

