"""
Observability Module - وحدة المراقبة
=====================================

مراقبة وتتبع النظام:
- Structured Logging
- Metrics Collection
- Distributed Tracing
- Health Checks
- Alerting
- System Collectors
"""

from distributed_cluster.observability.logging import (
    LogContext,
    LogLevel,
    StructuredLogger,
    log_context,
    get_logger,
    RotatingFileHandler,
    TimedRotatingFileHandler,
    LogCleaner,
    setup_logging,
)

from distributed_cluster.observability.metrics import (
    MetricsCollector,
    MetricType,
    MetricValue,
    Histogram,
)

from distributed_cluster.observability.health import (
    HealthCheck,
    HealthChecker,
    HealthReport,
    HealthStatus,
    Alert,
    AlertManager,
    AlertRule,
    AlertSeverity,
    AlertState,
    NotificationChannel,
    LogChannel,
    WebhookChannel,
    SlackChannel,
    create_standard_alert_rules,
)

from distributed_cluster.observability.prometheus import (
    PrometheusMetric,
    Counter,
    Gauge,
    Histogram as PrometheusHistogram,
    Summary,
    PrometheusRegistry,
    NebulaMetrics,
    PrometheusMiddleware,
    create_metrics_endpoint,
)

from distributed_cluster.observability.tracing import (
    Span,
    SpanEvent,
    SpanKind,
    SpanLink,
    SpanStatus,
    SpanExporter,
    ConsoleSpanExporter,
    OTLPSpanExporter,
    JaegerSpanExporter,
    Tracer,
    traced,
    get_tracer,
    set_tracer,
)

from distributed_cluster.observability.collectors import (
    CPUMetrics,
    MemoryMetrics,
    DiskMetrics,
    NetworkMetrics,
    GPUMetrics,
    ProcessMetrics,
    SystemCollector,
    MetricsReporter,
    PrometheusSystemCollector,
)

# Advanced Metrics
from distributed_cluster.observability.advanced_metrics import (
    MetricsAggregator,
    RequestMetrics,
    RequestMetricsCollector,
    SLODefinition,
    SLOMonitor,
    SLOStatus,
    SLOType,
    BusinessMetric,
    BusinessMetricsCollector,
    SlidingWindowCounter,
    create_default_slos,
    create_metrics_middleware,
    get_metrics_aggregator,
    track_latency,
    track_calls,
)

# Enhanced Logging
from distributed_cluster.observability.enhanced_logging import (
    EnhancedLogger,
    LoggerFactory,
    LogAggregator,
    ConsoleHandler,
    AsyncFileHandler,
    LogRecord,
    CorrelationContext,
    generate_correlation_id,
    get_correlation_id,
    set_correlation_id,
    get_trace_context,
    set_trace_context,
    with_correlation,
    log_execution,
    create_logging_middleware,
    LogLevel as EnhancedLogLevel,
    setup_logging as setup_enhanced_logging,
    get_logger as get_enhanced_logger,
)

# Comprehensive Health Checks
from distributed_cluster.observability.comprehensive_health import (
    HealthCheckManager,
    HealthCheckResult,
    HealthStatus as ComprehensiveHealthStatus,
    DependencyType,
    DependencyConfig,
    HealthCheck as ComprehensiveHealthCheck,
    TCPHealthCheck,
    HTTPHealthCheck,
    DNSHealthCheck,
    SSLCertificateCheck,
    PostgreSQLHealthCheck,
    RedisHealthCheck,
    CPUHealthCheck,
    MemoryHealthCheck,
    DiskHealthCheck,
    CompositeHealthCheck,
    DependencyChainCheck,
    ReadinessProbe,
    LivenessProbe,
    create_health_routes,
    setup_default_checks,
)

# Unified Manager
from distributed_cluster.observability.unified_manager import (
    UnifiedObservabilityManager,
    ObservabilityConfig,
    ObservabilityStatus,
    SystemStatus,
    create_observability_routes,
    create_observability_middleware,
    get_observability_manager,
    setup_observability,
    shutdown_observability,
)

__all__ = [
    # Logging
    "LogContext",
    "LogLevel",
    "StructuredLogger",
    "log_context",
    "get_logger",
    "RotatingFileHandler",
    "TimedRotatingFileHandler",
    "LogCleaner",
    "setup_logging",
    # Metrics
    "MetricsCollector",
    "MetricType",
    "MetricValue",
    "Histogram",
    # Health & Alerts
    "HealthCheck",
    "HealthChecker",
    "HealthReport",
    "HealthStatus",
    "Alert",
    "AlertManager",
    "AlertRule",
    "AlertSeverity",
    "AlertState",
    "NotificationChannel",
    "LogChannel",
    "WebhookChannel",
    "SlackChannel",
    "create_standard_alert_rules",
    # Prometheus
    "PrometheusMetric",
    "Counter",
    "Gauge",
    "PrometheusHistogram",
    "Summary",
    "PrometheusRegistry",
    "NebulaMetrics",
    "PrometheusMiddleware",
    "create_metrics_endpoint",
    # Tracing
    "Span",
    "SpanEvent",
    "SpanKind",
    "SpanLink",
    "SpanStatus",
    "SpanExporter",
    "ConsoleSpanExporter",
    "OTLPSpanExporter",
    "JaegerSpanExporter",
    "Tracer",
    "traced",
    "get_tracer",
    "set_tracer",
    # System Collectors
    "CPUMetrics",
    "MemoryMetrics",
    "DiskMetrics",
    "NetworkMetrics",
    "GPUMetrics",
    "ProcessMetrics",
    "SystemCollector",
    "MetricsReporter",
    "PrometheusSystemCollector",
    # Advanced Metrics
    "MetricsAggregator",
    "RequestMetrics",
    "RequestMetricsCollector",
    "SLODefinition",
    "SLOMonitor",
    "SLOStatus",
    "SLOType",
    "BusinessMetric",
    "BusinessMetricsCollector",
    "SlidingWindowCounter",
    "create_default_slos",
    "create_metrics_middleware",
    "get_metrics_aggregator",
    "track_latency",
    "track_calls",
    # Enhanced Logging
    "EnhancedLogger",
    "LoggerFactory",
    "LogAggregator",
    "ConsoleHandler",
    "AsyncFileHandler",
    "LogRecord",
    "CorrelationContext",
    "generate_correlation_id",
    "get_correlation_id",
    "set_correlation_id",
    "get_trace_context",
    "set_trace_context",
    "with_correlation",
    "log_execution",
    "create_logging_middleware",
    "EnhancedLogLevel",
    "setup_enhanced_logging",
    "get_enhanced_logger",
    # Comprehensive Health
    "HealthCheckManager",
    "HealthCheckResult",
    "ComprehensiveHealthStatus",
    "DependencyType",
    "DependencyConfig",
    "ComprehensiveHealthCheck",
    "TCPHealthCheck",
    "HTTPHealthCheck",
    "DNSHealthCheck",
    "SSLCertificateCheck",
    "PostgreSQLHealthCheck",
    "RedisHealthCheck",
    "CPUHealthCheck",
    "MemoryHealthCheck",
    "DiskHealthCheck",
    "CompositeHealthCheck",
    "DependencyChainCheck",
    "ReadinessProbe",
    "LivenessProbe",
    "create_health_routes",
    "setup_default_checks",
    # Unified Manager
    "UnifiedObservabilityManager",
    "ObservabilityConfig",
    "ObservabilityStatus",
    "SystemStatus",
    "create_observability_routes",
    "create_observability_middleware",
    "get_observability_manager",
    "setup_observability",
    "shutdown_observability",
]
