{{- if .Values.master.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebulacompute.fullname" . }}-master
  labels:
    {{- include "nebulacompute.master.labels" . | nindent 4 }}
  {{- with .Values.master.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.master.service.type }}
  ports:
    - port: {{ .Values.master.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.master.metrics.enabled }}
    - port: {{ .Values.master.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "nebulacompute.master.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.master.ha.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebulacompute.fullname" . }}-master-headless
  labels:
    {{- include "nebulacompute.master.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.master.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nebulacompute.master.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.web.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebulacompute.fullname" . }}-web
  labels:
    {{- include "nebulacompute.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nebulacompute.web.selectorLabels" . | nindent 4 }}
{{- end }}
